version: '2'

services:
  dokuwiki:
    image: ksala/dokuwiki:latest
    restart: always
    volumes:
      - data:/dokuwiki/data
      - plugins:/dokuwiki/lib/plugins
      - config:/dokuwiki/config
      - templates:/dokuwiki/lib/tpl
    ports:
      - 127.0.0.1:9001:80

volumes:
  data:
  plugins:
  config:
  templates:
